### PR TITLE
Fix line break

### PR DESCRIPTION
**Pull request by Adam1609**
{LINE} in lang.properties does not work. A small fix is applied, should be line break now

### CODE REVIEW

**Comment by Adam1609** [comment]
In 840b07d I also fix an error that doesn't show the not-enough-money in lang.properties

**Comment by kenygamer** [comment]
Seems good. Lint gave results, can you:

1. Remove [this line](https://github.com/kenygamer/CEShopGUI/blob/3b3fe3994c1677814f004777b8e0a72f998d47fe/src/kenygamer/CEShopGUI/command/CEShopCommand.php#L95) 
2.  Change
```php
$sender->addXp($exp);
```
to

```php
$sender->addXp($value);
```
in
https://github.com/kenygamer/CEShopGUI/blob/3b3fe3994c1677814f004777b8e0a72f998d47fe/src/kenygamer/CEShopGUI/command/TinkererCommand.php#L89

**Comment by Adam1609** [comment]
Should be perfect now.

**Comment by kenygamer** [comment]
Thank you. I'm going to merge this immediately.

**Pull request merged**
